/gait_node:
  ros__parameters:
    body_height: -0.06
    body_height_max: -0.03
    body_height_min: -0.08
    cmd_vel_timeout: 0.5
    cycle_time: 2.0
    default_angular_z: 0.0
    default_linear_x: 0.0
    default_linear_y: 0.0
    gait_pattern: tripod
    radial_distance: 0.27
    start_type_description_service: true
    step_height: 0.04
    step_length_max: 0.05
    tick_rate: 50.0
    time_from_start_factor: 2.0
    use_sim_time: true

